### ISSUE TITLE
blue spells missing from valid spell list

### ISSUE THREAD

**Issue by disarrayed** [bnetcc/BNETccXI#8]
**_Additional Information_: Ninji asked for a reminder to add blue spells to the valid spell list**

**Comment by khoa002** [comment]
Any info on specific spell that is missing is appreciated, thanks!

**Comment by disarrayed** [comment]
Paralyzing Triad, Thrashing Assault, Diffusion Ray, Sinker Drill. That is the ones I know for sure for now.

**Comment by Ninjistix** [comment]
I might have fixed them but the server requires a restart

**Comment by Ninjistix** [comment]
need to verify this has been addressed in next server restart.
